### ISSUE TITLE
Joining issue

### ISSUE THREAD

**Issue by TrolliWurm** [Zenoryne/DiscSpam#31]
The Joining issue is still up

![image](https://user-images.githubusercontent.com/68162179/192400701-e5df883f-23f5-4fb3-b9d3-f6094ddc6ce0.png)

**Comment by ghost** [comment]
No PR's have been made since the last issue, so yeah it's not fixed.

**Comment by Soliux** [comment]
I will be taking a look at this a little later on today. I think discord has had an update recently to their join endpoint so I will sort it out and then push it to the repo and close this comment once I have done that.

**Comment by ghost** [comment]
> I will be taking a look at this a little later on today. I think discord has had an update recently to their join endpoint so I will sort it out and then push it to the repo and close this comment once I have done that.

You need matching TLS fingerprint, cookies and good tokens.

**Comment by anarchy1337x** [comment]
Stop buying those walmart tokens, and actually use correct terminology when creating an issue. Also please be more specific.

**Comment by Soliux** [comment]
After doing some investigation it seems that your tokens had gotten flagged and discord was serving them a captcha... as of right now the tool does not support captcha for joining, I am extremely busy with other things, but I will get onto adding this feature soon. Anyone who sees this and would like to write the code for the captcha on join I am open to prs otherwise this is closed.
