### ISSUE TITLE
Way of communicating

### ISSUE THREAD

**Issue by ghost** [Zenoryne/DiscSpam#8]
Is it possible to open a discussion to keep track of recent commits, or do you have discord ? would be easier

**Comment by Sympthey** [comment]
As of right now I do not have anything like that where I am telling people of the recent commits. I do have a discord I use to talk to people which is on my github profile, feel free to contact me on there if there is any suggestions you would like.

I will definitely look into create some form of discussion so that people can keep track of the repo updates. For right now I just suggest you come back whenever you are going to use the tool to make sure you have the latest version :)
